In [1]:
import numpy as np

numpy is used to do numeric calucaltions using array it is like python list but there is different python list is slower and uses high memeory useage than the numpy array and the most the delvopers uses numpys to quick caluclations

they are three types of array in numpy 1d 2d and 3d 3d is used for dl and image processing in futher

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(c))

1
2
3


In [20]:
b.size

6

In [15]:
a.dtype

dtype('int64')

In [16]:
b.size

6

Special Arrays


In [25]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
np.ones(2)

array([1., 1.])

In [27]:
np.full((3,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [45]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [30]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [31]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
np.linspace(10,100,6)# the diff btw the arange and line spane is on is used for print the differnce vaalue one is used for print the exact same value giben in parameters

array([ 10.,  28.,  46.,  64.,  82., 100.])

In [36]:
np.random.rand(2)

array([0.05436498, 0.35915876])

In [38]:
np.random.rand(2,3,4)

array([[[0.6105948 , 0.75828899, 0.23677842, 0.4604471 ],
        [0.20534928, 0.30903881, 0.50715974, 0.62801516],
        [0.80942846, 0.801832  , 0.62899397, 0.26094652]],

       [[0.76810251, 0.44456691, 0.15234421, 0.23076405],
        [0.30493301, 0.64772515, 0.05671747, 0.72638077],
        [0.49748321, 0.17525672, 0.02714305, 0.99967537]]])

In [49]:
np.random.randint(2,88)

23

In [50]:
c[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
c


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [54]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

In [55]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [56]:
c[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
c[-1]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [62]:
c[0,0,0]

np.int64(1)

In [63]:
c[2,2,1]

np.int64(26)

In [73]:
c[2:]

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [74]:
c[:1]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [77]:
c[-2:
]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [78]:
c[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [80]:
c[:,1]

array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24]])

In [82]:
c[0:1]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [83]:
c[:,0:1]

array([[[ 1,  2,  3]],

       [[10, 11, 12]],

       [[19, 20, 21]]])

In [84]:
c[c>1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27])

In [85]:
c>1

array([[[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [86]:
c[:,1]

array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24]])

In [89]:
#Array Operations & Broadcasting
s = np.array([10000,20000,3000,40000])
s

array([10000, 20000,  3000, 40000])

In [90]:
s +=500

In [92]:
s ''' in python list we  have to use the for loop here we can directly add the value to the numpy array that why for this calucaltion
it is so easy to for numoy than list
same way we use - * / % etc
'''


array([10500, 20500,  3500, 40500])

In [97]:
a

array([1, 2, 3, 4])

In [98]:
d = np.array([1,2,3,4])

In [100]:
a+d # here the array should be in same size ans same shape same like - * / % etc

array([2, 4, 6, 8])

Broadcasting You might think:

"There is only one number (5). How can NumPy add it to three values?"

NumPy internally broadcasts the value.

It treats it like:

5 5 5

So it actually performs:

10 + 5

20 + 5

30 + 5

Add	a +

Subtract	a - 5

Multiply	a * 2

Divide	a / 10

Array Addition	a + b

Array Multiplication	a * b

Comparison	a > 25

Filtering	a[a > 25]

Broadcasting	a + 5 (5 is applied to every element)

In [103]:
#Comparison Operators
a>2
# same like < == >=

array([False, False,  True,  True])